### PR TITLE
265/pom-refactor-bugs

### LINKED ISSUE #236: [PE-D] Changing name during pomodoro
When a pomodoro for a task is running and i change the name, the name in the list changes but not the one on the pomodoro countdown timer. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: joycelynteo/ped#2

### LINKED ISSUE #265: Pomodoro refactor and bugs
Goal: Reduce the responsibility of prompts in MainWindow and load onto PomodoroManager.
Edit existing bugs/fixes-needed:
-- Update Pommed Task Title (on edit, on done, on time-up)
-- Don't allow tm <= 0

### PR DESCRIPTION
**Pull request by Hardoh**
Reduce the responsibility of prompts in MainWindow and load onto PomodoroManager.

Edit existing bugs/fixes-needed:
-- Update Pommed Task Title (on edit, on done, on time-up)
-- Don't allow tm <= 0

### CODE REVIEW

File: src/main/java/seedu/address/logic/PomodoroManager.java [hunk 1]
```diff
@@ -314,4 +326,118 @@ public void doneTask() {
...
+                CommandResult commandResult =
+                    new CommandResult("Alright, back to neutral!", false, false);
+                resultDisplay.setFeedbackToUser(commandResult.getFeedbackToUser());
+                setPromptState(PROMPT_STATE.NONE);
+                reset();
+                mainWindow.setDefaultCommandExecutor();
+                return commandResult;
+            }
+            try {
+                //PomCommand pc = (PomCommand) (new TaskListParser().parseCommand(commandText));
```
Comment (artlee06) [inline src/main/java/seedu/address/logic/PomodoroManager.java:398]: Perhaps remove some of these comments

File: src/main/java/seedu/address/logic/PomodoroManager.java [hunk 2]
```diff
@@ -142,7 +154,7 @@ public void unpause() throws NullPointerException {
 
     public void reset() {
         timerLabel.textProperty().unbind();
-        timerLabel.setText("POM");
+        pomodoroDisplay.reset();
```
Comment (artlee06) [inline src/main/java/seedu/address/logic/PomodoroManager.java:157]: Does this mean 25:00 is displayed instead of POM?

File: src/main/java/seedu/address/ui/PomodoroDisplay.java [hunk 3]
```diff
@@ -38,6 +38,18 @@ public void setTaskInProgressText(String toDisplay) {
...
+    public void setDefaultTimeText(String defaultTimeText) {
+        this.default_timer = defaultTimeText;
+    }
+
+    public void reset() {
+        this.taskInProgressText = DEFAULT_TASK_IN_PROGRESS;
+        this.timerText = default_timer;
+
+        taskInProgress.setText(taskInProgressText);
+        timer.setText(timerText);
```
Comment (artlee06) [inline src/main/java/seedu/address/ui/PomodoroDisplay.java:50]: Ah yes so it is set 25:00

**Review by artlee06 — APPROVED** [review]
LGTM! MainWindow is a lot cleaner now

File: src/main/java/seedu/address/logic/PomodoroManager.java (hunk 2 above)
Comment (Hardoh) [reply src/main/java/seedu/address/logic/PomodoroManager.java:157]: That's right. "POM" no longer shows. Goes back to the user's specified default timer.
