### PR TITLE
Bug/148 reminder deleted after edit

### LINKED ISSUE #148: Bug/Reminder deleted after edit command

### PR DESCRIPTION
**Pull request by artlee06**
Fixed the bug, when you edit any other field, reminders are retained. Also, I did some patchwork for the default mood on startup please test that @FyonnOh

### CODE REVIEW

File: src/main/java/seedu/address/model/Pet.java [hunk 1]
```diff
@@ -93,11 +93,17 @@ public String getExp() {
 
     @Override
     public String getMood() {
+        if (this.mood == null) {
```
Comment (FyonnOh) [inline src/main/java/seedu/address/model/Pet.java:96]: Thank you! I missed out this part when writing the code oops

**Review by FyonnOh — APPROVED** [review]
Good job! Minor fixes done to resolve the bug. LGTM!
